"""feat: added index on field model user id

Revision ID: 01fa725afe79
Revises: 7e291035284d
Create Date: 2026-01-12 18:34:20.023229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01fa725afe79'
down_revision: Union[str, Sequence[str], None] = '7e291035284d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_farmfields_user_id'), 'farmfields', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_farmfields_user_id'), table_name='farmfields')
    # ### end Alembic commands ###
